apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.labels.app }}
    tier: {{ .Values.frontend.labels.tier }}
spec:
  type: {{ .Values.frontend.serviceType }}
  ports:
    - port: {{ .Values.frontend.port }}
      name: http
  selector:
    app: {{ .Values.frontend.labels.app }}
    tier: {{ .Values.frontend.labels.tier }}
