apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.redisMaster.name }}
  labels:
    app: {{ .Values.redisMaster.app }}
    role: {{ .Values.redisMaster.role }}
    tier: {{ .Values.redisMaster.tier }}
spec:
  replicas: {{ .Values.redisMaster.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.redisMaster.app }}
      role: {{ .Values.redisMaster.role }}
      tier: {{ .Values.redisMaster.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.redisMaster.app }}
        role: {{ .Values.redisMaster.role }}
        tier: {{ .Values.redisMaster.tier }}
    spec:
      name: {{ .Values.redisMaster.name }}
      containers:
        - name: {{ .Values.redisMaster.image.name }}
          image: "{{ .Values.redisMaster.image.repository }}:{{ .Values.redisMaster.image.tag }}"
          imagePullPolicy: {{ .Values.redisMaster.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redisMaster.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
