apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: {{ .Values.redisSlave.app }}
    role: {{ .Values.redisSlave.role }}
    tier: {{ .Values.redisSlave.tier }}
spec:
  replicas: {{ .Values.redisSlave.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.redisSlave.app }}
      role: {{ .Values.redisSlave.role }}
      tier: {{ .Values.redisSlave.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.redisSlave.app }}
        role: {{ .Values.redisSlave.role }}
        tier: {{ .Values.redisSlave.tier }}
    spec:
      name: slaves
      containers:
        - name: {{ .Values.redisSlave.image.name }}
          image: "{{ .Values.redisSlave.image.repository }}:{{ .Values.redisSlave.image.tag }}"
          imagePullPolicy: {{ .Values.redisSlave.image.pullPolicy }}
          env:
            - name: GET_HOSTS_FROM
              value: {{ .Values.redisSlave.discoveryMechanism }}
          ports:
            - name: {{ .Values.redisSlave.name }}
              containerPort: {{ .Values.redisSlave.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
