apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisMasterService.name }}
  labels:
    app: {{ .Values.redisMasterService.labels.app }}
    role: {{ .Values.redisMasterService.labels.role }}
    tier: {{ .Values.redisMasterService.labels.tier }}
spec:
  type: {{ .Values.redisMasterService.type }}
  ports:
    - port: {{ .Values.redisMasterService.port }}
      targetPort: {{ .Values.redisMasterService.port }}
  selector:
    app: {{ .Values.redisMasterService.selector.app }}
    role: {{ .Values.redisMasterService.selector.role }}
    tier: {{ .Values.redisMasterService.selector.tier }}
