apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: {{ .Values.redisSlave.app }}
    role: {{ .Values.redisSlave.role }}
    tier: {{ .Values.redisSlave.tier }}
spec:
  replicas: {{ .Values.slaveReplicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gke-guestbook-tutorial.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ .Values.redisSlave.app }}
      role: {{ .Values.redisSlave.role }}
      tier: {{ .Values.redisSlave.tier }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gke-guestbook-tutorial.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ .Values.redisSlave.app }}
        role: {{ .Values.redisSlave.role }}
        tier: {{ .Values.redisSlave.tier }}
    spec:
      name: slaves
      containers:
        - name: test1
          image: "{{ .Values.redisSlaveImage.repository }}:{{ .Values.redisSlaveImage.tag }}"
          imagePullPolicy: {{ .Values.redisSlaveImage.pullPolicy }}
          env:
            - name: GET_HOSTS_FROM
              value: {{ .Values.redisSlave.discoveryMechanism }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
